enum SteloSymbol {
  SS_nop = -1,
  SS_push0, /* 0 */
  SS_push1, /* 1 */
  SS_pushShort, /* 2 */
  SS_pushFloat, /* 3 */
  SS_abs, /* 4 */
  SS_acos, /* 5 */
  SS_aimHigh, /* 6 */
  SS_and, /* 7 */
  SS_asin, /* 8 */
  SS_atan, /* 9 */
  SS_broadcast, /* 10 */
  SS_call, /* 11 */
  SS_clearAll, /* 12 */
  SS_clearGraphics, /* 13 */
  SS_clearTurtles, /* 14 */
  SS_cos, /* 15 */
  SS_createPatch, /* 16 */
  SS_createTurtles, /* 17 */
  SS_dec, /* 18 */
  SS_diffuse, /* 19 */
  SS_diffuse4, /* 20 */
  SS_direction, /* 21 */
  SS_div, /* 22 */
  SS_drop, /* 23 */
  SS_dup, /* 24 */
  SS_dx, /* 25 */
  SS_dy, /* 26 */
  SS_equal, /* 27 */
  SS_exp, /* 28 */
  SS_exp10, /* 29 */
  SS_forward, /* 30 */
  SS_getBreedId, /* 31 */
  SS_getBreedVar, /* 32 */
  SS_getId, /* 33 */
  SS_getVar, /* 34 */
  SS_getX, /* 35 */
  SS_getY, /* 36 */
  SS_hatch, /* 37 */
  SS_inv, /* 38 */
  SS_jump, /* 39 */
  SS_jumpIfFalse, /* 40 */
  SS_jumpIfTrue, /* 41 */
  SS_kill, /* 42 */
  SS_less, /* 43 */
  SS_lessEqual, /* 44 */
  SS_ln, /* 45 */
  SS_log, /* 46 */
  SS_minus, /* 47 */
  SS_mod, /* 48 */
  SS_mul, /* 49 */
  SS_multiplyBy, /* 50 */
  SS_not, /* 51 */
  SS_nsum, /* 52 */
  SS_nsum4, /* 53 */
  SS_or, /* 54 */
  SS_patchAt, /* 55 */
  SS_plus, /* 56 */
  SS_randomFromTo, /* 57 */
  SS_return, /* 58 */
  SS_returnValue, /* 59 */
  SS_rounded, /* 60 */
  SS_scaleColorFromTo, /* 61 */
  SS_setBreedVarTo, /* 62 */
  SS_setColorTo, /* 63 */
  SS_setHeading, /* 64 */
  SS_setPatchColorTo, /* 65 */
  SS_setVarTo, /* 66 */
  SS_setX, /* 67 */
  SS_setY, /* 68 */
  SS_sin, /* 69 */
  SS_sqrt, /* 70 */
  SS_stop, /* 71 */
  SS_stopAll, /* 72 */
  SS_swap, /* 73 */
  SS_tan, /* 74 */
  SS_truncated, /* 75 */
  SS_turtleAt, /* 76 */
  SS_turtlesCount, /* 77 */
  SS_xyOf, /* 78 */
};
