SystemOrganization addCategory: #SteloSquelch!
SystemOrganization addCategory: #'SteloSquelch-Blocks'!
SystemOrganization addCategory: #'SteloSquelch-CodeGenerator'!
SystemOrganization addCategory: #'SteloSquelch-Manifest'!
SystemOrganization addCategory: #'SteloSquelch-Object IO'!
SystemOrganization addCategory: #'SteloSquelch-Stelost'!
SystemOrganization addCategory: #'SteloSquelch-Translation'!
SystemOrganization addCategory: #'SteloSquelch-UI-Dialogs'!
SystemOrganization addCategory: #'SteloSquelch-UI-Panes'!
SystemOrganization addCategory: #'SteloSquelch-UI-Support'!
